version: 2
jobs:
  publish-nodejs810:
    docker:
        - image: circleci/nodejs:8
    steps:
      - checkout
      - run:
          name: Install publish dependencies
          command: sudo pip install -U awscli
      - run:
          name: Publish layer
          command: |
            cd nodejs
            ./publish-layers.sh nodejs8.10
  publish-nodejs10x:
    docker:
        - image: circleci/nodejs:10
    steps:
      - checkout
      - run:
          name: Install publish dependencies
          command: sudo pip install -U awscli
      - run:
          name: Publish layer
          command: |
            cd nodejs
            ./publish-layers.sh nodejs10.x
  publish-python27:
    docker:
      - image: circleci/python:2.7
    steps:
      - checkout
      - run:
          name: Install publish dependencies
          command: sudo pip install -U awscli
      - run:
          name: Publish layer
          command: |
            cd python
            ./publish-layers.sh python2.7
  publish-python36:
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - run:
          name: Install publish dependencies
          command: sudo pip install -U awscli
      - run:
          name: Publish layer
          command: |
            cd python
            ./publish-layers.sh python3.6
  publish-python37:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - run:
          name: Install publish dependencies
          command: sudo pip install -U awscli
      - run:
          name: Publish layer
          command: |
            cd python
            ./publish-layers.sh python3.7

workflows:
  version: 2
  publish-layers:
    jobs:
      - publish-nodejs810:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v[0-9]+(\.[0-9]+)*_nodejs/
      - publish-nodejs10x:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v[0-9]+(\.[0-9]+)*_nodejs/
      - publish-python27:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v[0-9]+(\.[0-9]+)*_python/
      - publish-python36:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v[0-9]+(\.[0-9]+)*_python/
      - publish-python37:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v[0-9]+(\.[0-9]+)*_python/
